import { Inter } from '@next/font/google';
import SignIn from './auth/signin';
import { signIn } from 'next-auth/react';
import styles from '@/styles/Home.module.css';
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <button
          onClick={() => {
            signIn();
          }}
        >
          Login
        </button>
      </main>
      <footer className={styles.footer}></footer>
      {/* <SignIn></SignIn> */}
    </div>
  );
}
